import 'package:get/get.dart';

class TranslatedStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Home': 'Home',
          'New folder': 'New folder',
          'Search': 'Search',
          'Edit': 'Edit',
          'Enter new title': 'Enter new title',
          'Confirm': 'Confirm',
          'Cancel': 'Cancel',
          'Delete': 'Delete',
          'Error': 'Error',
          'Enter at least one character': 'Enter at least one character',
          'New title was created': 'New title was created',
          'The title already exists': 'The title already exists',
          'Could not launch this page': 'Could not launch this page',
          'Drag and drop': 'Drag and drop',
          'Something went wrong...': 'Something went wrong...',
          'Do you want to exit the app?': 'Do you want to exit the app?',
          'Yes': 'Yes',
          'No': 'No',
          'Enter new name': 'Enter new name',
          'Folder name has been changed': 'Folder name has been changed',
          'The folder with this name already exists':
              'The folder with this name already exists',
          'Enter folder name...': 'Enter folder name...',
          'Save': 'Save',
          'This folder has been added to the list':
              'This folder has been added to the list',
          'Search...': 'Search...',
        },
        'es': {
          'Home': 'Inicio',
          'New folder': 'Nueva carpeta',
          'Search': 'Buscar',
          'Edit': 'Editar',
          'Enter new title': 'Nuevo título',
          'Confirm': 'Confirmar',
          'Cancel': 'Cancelar',
          'Delete': 'Eliminar',
          'Error': 'Error',
          'Enter at least one character': 'Ingrese al menos un carácter',
          'New title was created': 'Nuevo título creado',
          'The title already exists': 'Este título ya existe',
          'Could not launch this page': 'Imposible acceder a la página',
          'Drag and drop': 'Arrastrar y soltar',
          'Something went wrong...': 'Algo salió mal...',
          'Do you want to exit the app?': '¿Quiere salir de la aplicación?',
          'Yes': 'Si',
          'No': 'No',
          'Enter new name': 'Ingrese nuevo nombre',
          'Folder name has been changed': 'Nuevo nombre asignado a la carpeta',
          'The folder with this name already exists':
              'La carpeta con este nombre ya existe',
          'Enter folder name...': 'Ingrese nombre de la carpeta...',
          'Save': 'Guardar',
          'This folder has been added to the list':
              'Esta carpeta ha sido añadida a la lista',
          'Search...': 'Buscar...',
        },
        'ru': {
          'Home': 'Главная',
          'New folder': 'Новая папка',
          'Search': 'Найти',
          'Edit': 'Редактировать',
          'Enter new title': 'Переименовать ссылку',
          'Confirm': 'Готово',
          'Cancel': 'Отмена',
          'Delete': 'Удалить',
          'Error': 'Ошибка',
          'Enter at least one character': 'Введите как минимум один символ',
          'New title was created': 'Название ссылки изменено',
          'The title already exists': 'Это название уже используется',
          'Could not launch this page': 'Не удалось запустить эту страницу',
          'Drag and drop': 'Перетащить',
          'Something went wrong...': 'Что-то пошло не так...',
          'Do you want to exit the app?': 'Хотите выйти из приложения?',
          'Yes': 'Да',
          'No': 'Нет',
          'Enter new name': 'Введите новое название',
          'Folder name has been changed': 'Название папки изменено',
          'The folder with this name already exists':
              'Папка с таким названием уже существует',
          'Enter folder name...': 'Введите название папки...',
          'Save': 'Сохранить',
          'This folder has been added to the list':
              'Эта папка добавлена ​​в список',
          'Search...': 'Найти...',
        }
      };
}
